
//#define Debug

// App
#define WIN_WIDTH 1440
#define WIN_HEIGHT 900
#define SYSTEM_FONT_SIZE 15
#define TITLE_SCREEN_FONT_SIZE 40

// GameScreen
#define GSCR_BUTTON_TEXT_SIZE 45
#define GSCR_BUTTON_WIDTH 200
#define GSCR_BUTTON_HEIGHT 50
#define GSCR_BUTTON_OUT_LINE_THICKNESS 2.f





// RollingWindow
#define RWIN_WIN_SCALE .8f
#define RWIN_TEXT_SCALE 1.9f
#define RWIN_TEXT_SIZE 135
#define RWIN_TEXT_COLOR_NORMAL sf::Color(255, 255, 255, 255)
#define RWIN_ACCELERATE_SPEED 20.f
#define RWIN_REFRESH_TIME 0.05f
#define RWIN_MAX_SPEED 2000.f
#define RWIN_MIN_SPEED 200.f
#define RWIN_ERROR_MARGIN 50
#define INIT_MESSAGE "CSSA"
#define BG_PARTICLE_QT 500
#define BG_PARTICLE_SPEED 55.f
#define BG_PARTICLE_TIME 4.5f
#define ANIM_PARTICLE_QT 50
#define ANIM_PARTICLE_QT_HIGH 400
#define ANIM_PARTICLE_SPEED 450.f
#define ANIM_PARTICLE_TIME 1.2f